import React, { memo } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { Card } from '@/components/ui/Card';
import { Notification } from '@/types';
import { formatDateTime } from '@/utils';
import { useAppTheme } from '@/hooks/useAppTheme';
export const NotificationListItem = memo(function NotificationListItem({ item, onPress }: { item: Notification; onPress: () => void }) { const { colors } = useAppTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={`${item.read ? 'Read' : 'Unread'} notification: ${item.message}`} accessibilityHint={item.read ? undefined : 'Marks this notification as read'} onPress={onPress} style={({ pressed }) => pressed && styles.pressed}><Card style={[styles.card, !item.read && { borderColor: `${colors.tint}55` }]}><View style={styles.row}><View style={[styles.iconWrap, { backgroundColor: item.read ? colors.surfaceMuted : `${colors.tint}18` }]}><MaterialCommunityIcons name={getIconName(item.category)} size={20} color={colors.tint} /></View><View style={styles.content}><Text style={[styles.message, { color: colors.text }]}>{item.message}</Text><Text style={[styles.date, { color: colors.muted }]}>{formatDateTime(item.createdAt)}</Text></View>{!item.read && <View style={[styles.dot, { backgroundColor: colors.tint }]} />}</View></Card></Pressable>; }, (previous, next) => previous.item === next.item);
function getIconName(category: Notification['category']) { if (category === 'case') return 'folder-alert-outline'; if (category === 'threat') return 'radar'; if (category === 'sos') return 'alarm-light-outline'; return 'bell-outline'; }
const styles = StyleSheet.create({ card: { marginBottom: 10 }, content: { flex: 1 }, date: { fontSize: 11, marginTop: 5 }, dot: { borderRadius: 4, height: 8, width: 8 }, iconWrap: { alignItems: 'center', borderRadius: 14, height: 44, justifyContent: 'center', width: 44 }, message: { fontSize: 14, fontWeight: '600', lineHeight: 20 }, pressed: { opacity: 0.72 }, row: { alignItems: 'center', flexDirection: 'row', gap: 12 } });
