import React, { useState } from 'react';
import { Alert, Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { ScreenContainer } from '@/components/ui/ScreenContainer';
import { Typography } from '@/components/ui/Typography';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { useCaseStore } from '@/store/caseStore';
import { useSettingsStore } from '@/store/settingsStore';
import { useAppTheme } from '@/hooks/useAppTheme';
export default function EmergencySosScreen() {
  const { colors } = useAppTheme(); const createCase = useCaseStore((state) => state.createCase); const isLoading = useCaseStore((state) => state.isMutating); const error = useCaseStore((state) => state.mutationError); const emergencyContact = useSettingsStore((state) => state.emergencyContact); const [location, setLocation] = useState(''); const [context, setContext] = useState('Live call pressure or demand for immediate transfer.');
  const createSosCase = async () => { const caseItem = await createCase({ title: 'Emergency SOS escalation', description: context.trim() || 'Citizen triggered emergency SOS from mobile app.', category: 'digital_arrest', location: location.trim() || undefined, riskLevel: 'critical' }); if (!caseItem) return; router.replace({ pathname: '/(tabs)/case/[id]', params: { id: caseItem.id } }); };
  const callNumber = async (value: string) => { const supported = await Linking.canOpenURL(`tel:${value}`); if (supported) await Linking.openURL(`tel:${value}`); else Alert.alert('Dialer unavailable', `Call ${value} from your phone dialer.`); };
  return <ScreenContainer scroll><Pressable accessibilityRole="button" accessibilityLabel="Go back" style={[styles.backButton, { backgroundColor: colors.surface, borderColor: colors.border }]} onPress={() => router.back()}><MaterialCommunityIcons name="arrow-left" size={21} color={colors.text} /></Pressable><Text style={[styles.eyebrow, { color: colors.danger }]}>URGENT SUPPORT</Text><Typography variant="h1">Emergency SOS</Typography><Card tone="danger" style={styles.hero}><View style={[styles.siren, { backgroundColor: `${colors.danger}16` }]}><MaterialCommunityIcons name="shield-alert-outline" size={34} color={colors.danger} /></View><Text style={[styles.heroTitle, { color: colors.text }]}>Pause. You are not alone.</Text><Text style={[styles.heroText, { color: colors.muted }]}>Use SOS when someone is pressuring you to transfer money, stay on a call, or share confidential information.</Text></Card><Card style={styles.section}><Text style={[styles.sectionTitle, { color: colors.text }]}>What is happening?</Text><Input label="Your location" value={location} onChangeText={setLocation} placeholder="City, district, or landmark" /><Input label="Brief context" value={context} onChangeText={setContext} multiline numberOfLines={4} textAlignVertical="top" style={styles.contextInput} /></Card>{error && <Text accessibilityRole="alert" style={[styles.calloutText, { color: colors.danger }]}>{error}</Text>}<Button title="Create SOS case" iconName="shield-alert-outline" variant="danger" loading={isLoading} onPress={createSosCase} /><View style={[styles.callout, { borderColor: colors.border }]}><MaterialCommunityIcons name="phone-in-talk-outline" size={18} color={colors.tint} /><Text style={[styles.calloutText, { color: colors.muted }]}>If a transfer is in progress, call 1930 immediately.</Text></View><Button title="Call 1930" iconName="phone-alert-outline" variant="outline" onPress={() => callNumber('1930')} /><Button title={`Call ${emergencyContact}`} iconName="phone-outline" variant="ghost" onPress={() => callNumber(emergencyContact)} /></ScreenContainer>;
}
const styles = StyleSheet.create({ backButton: { alignItems: 'center', borderRadius: 14, borderWidth: 1, height: 44, justifyContent: 'center', marginBottom: 20, width: 44 }, callout: { alignItems: 'center', borderTopWidth: 1, flexDirection: 'row', gap: 9, marginTop: 14, paddingTop: 16 }, calloutText: { flex: 1, fontSize: 13, lineHeight: 18 }, contextInput: { minHeight: 106 }, eyebrow: { fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginBottom: 10 }, hero: { alignItems: 'center', marginBottom: 14, paddingVertical: 24 }, heroText: { fontSize: 14, lineHeight: 20, marginTop: 8, textAlign: 'center' }, heroTitle: { fontSize: 21, fontWeight: '700', letterSpacing: -0.4, marginTop: 15 }, section: { marginBottom: 12 }, sectionTitle: { fontSize: 16, fontWeight: '700', marginBottom: 5 }, siren: { alignItems: 'center', borderRadius: 20, height: 64, justifyContent: 'center', width: 64 } });
