import { Activity, Building2, CircleAlert, RadioTower, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { CapabilityNotice, Card, EmptyState, ErrorState, MetricCard, PageHeader, RiskBadge, SectionHeader, Skeleton } from '@/components/ui';
import { useCases, useHealth, useNotifications, useThreats } from '@/data/queries';
import { formatRelative, inferRisk, titleCase } from '@/lib/format';

export function CommandCenter() {
  const cases = useCases(); const threats = useThreats(); const notifications = useNotifications(); const health = useHealth();
  if (cases.isLoading || threats.isLoading) return <Skeleton rows={10} />;
  if (cases.isError) return <ErrorState error={cases.error} retry={() => void cases.refetch()} />;
  const active = (cases.data ?? []).filter((item) => item.status !== 'CLOSED');
  const severe = active.filter((item) => ['critical', 'high'].includes(inferRisk(item)));
  const regions = Object.entries((threats.data?.items ?? []).reduce<Record<string, number>>((map, threat) => ({ ...map, [threat.region]: (map[threat.region] ?? 0) + 1 }), {})).sort((a, b) => b[1] - a[1]);
  return <><PageHeader eyebrow="National operations" title="Command center" description="A high-level operational picture assembled from current cases, advisories, notifications and service health." actions={<span className="sync-label"><i /> Polling every 60 seconds</span>} /><div className="metric-grid"><MetricCard label="Open investigations" value={active.length} detail={`${severe.length} high-priority signals`} icon={<Activity size={19} />} /><MetricCard label="Escalated" value={active.filter((item) => item.status === 'ESCALATED').length} detail="Workflow state from case service" icon={<CircleAlert size={19} />} /><MetricCard label="Regions monitored" value={regions.length} detail="Reported by threat advisories" icon={<Building2 size={19} />} /><MetricCard label="Gateway" value={health.data?.status ? titleCase(health.data.status) : 'Unavailable'} detail={health.isError ? 'Health check failed' : 'Health endpoint responding'} icon={<RadioTower size={19} />} /></div>
    <div className="dashboard-grid"><Card className="span-8"><SectionHeader title="Cases requiring command attention" description="Active records with high or critical risk signals." />{severe.length === 0 ? <EmptyState title="No high-priority cases" description="The current case set contains no active high or critical risk signals." /> : <div className="record-list">{severe.slice(0, 8).map((item) => <Link className="record-row" to={`/cases/${item.id}`} key={item.id}><div className="record-row__marker"><ShieldCheck size={17} /></div><div><small className="mono">{item.id}</small><strong>{item.title}</strong><p>{item.location || 'Location not supplied'}</p></div><div><RiskBadge value={inferRisk(item)} /><span>{formatRelative(item.updatedAt)}</span></div></Link>)}</div>}</Card><Card className="span-4"><SectionHeader title="Advisory distribution" description="Regions represented in the current public threat feed." />{regions.length === 0 ? <EmptyState title="No regional data" description="Threat advisories have not returned regional classifications." /> : <div className="distribution-list">{regions.slice(0, 8).map(([region, count]) => <div key={region}><span>{region}</span><div><i style={{ width: `${Math.max(12, count / regions[0][1] * 100)}%` }} /></div><strong>{count}</strong></div>)}</div>}</Card><Card className="span-12"><SectionHeader title="Operational pulse" description="Most recent notifications received from the backend." /><div className="alert-strip">{(notifications.data ?? []).slice(0, 4).map((item) => <article key={item.id}><Activity size={18} /><div><strong>{item.message}</strong><span>{formatRelative(item.createdAt)}</span></div></article>)}</div></Card></div>
    <CapabilityNotice title="Realtime command channels are not configured">The backend exposes request-response APIs but no WebSocket or server-sent event contract. This view uses transparent 60-second polling and never presents simulated live activity.</CapabilityNotice></>;
}
