import { ExternalLink, FileSearch, Fingerprint } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { CapabilityNotice, Card, DataTable, EmptyState, ErrorState, PageHeader, Pagination, RiskBadge, SearchField, Skeleton } from '@/components/ui';
import { useCases } from '@/data/queries';
import { formatDate, safeReference, titleCase } from '@/lib/format';
import type { Evidence } from '@/types';
import { ROUTES } from '@/app/routes';

interface IndexedEvidence extends Evidence { caseTitle: string; caseId: string }
const PAGE_SIZE = 12;
export function EvidenceExplorer() {
  const query = useCases(); const [search, setSearch] = useState(''); const [type, setType] = useState('ALL'); const [page, setPage] = useState(1); const [selected, setSelected] = useState<IndexedEvidence | null>(null);
  const all = useMemo(() => (query.data ?? []).flatMap((item) => (item.evidence ?? []).map((evidence) => ({ ...evidence, caseId: item.id, caseTitle: item.title }))), [query.data]);
  const filtered = useMemo(() => all.filter((item) => type === 'ALL' || item.type === type).filter((item) => `${item.id} ${item.label} ${item.notes ?? ''} ${item.caseId} ${item.caseTitle}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()), [all, search, type]);
  const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  return <><PageHeader eyebrow="Evidence operations" title="Evidence explorer" description="Search and inspect evidence metadata attached to the official case record." /><Card><div className="toolbar"><SearchField value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search evidence ID, label or case" /><select value={type} onChange={(event) => { setType(event.target.value); setPage(1); }} aria-label="Filter evidence type"><option value="ALL">All evidence types</option>{['audio', 'image', 'video', 'document', 'chat', 'link', 'note'].map((value) => <option key={value} value={value}>{titleCase(value)}</option>)}</select></div>{query.isLoading ? <Skeleton rows={8} /> : query.isError ? <ErrorState error={query.error} retry={() => void query.refetch()} /> : visible.length === 0 ? <EmptyState icon={<FileSearch size={22} />} title="No evidence found" description="Evidence references attached to cases will be indexed here." /> : <><DataTable headers={['Evidence', 'Case', 'Type', 'Recorded']} >{visible.map((item) => <tr key={item.id} className="clickable-row" onClick={() => setSelected(item)}><td><span className="table-primary"><strong>{item.label}</strong><span className="mono">{item.id}</span></span></td><td><Link to={ROUTES.dashboard.case(item.caseId)}>{item.caseTitle}</Link></td><td><RiskBadge value={item.type} /></td><td className="mono table-date">{formatDate(item.createdAt)}</td></tr>)}</DataTable><Pagination page={page} pages={pages} onChange={setPage} /></>}</Card><CapabilityNotice title="Chain of custody is not exposed by the backend">The current evidence API returns metadata and reference URIs only. This interface does not fabricate custody events, integrity hashes, or AI classifications.</CapabilityNotice>{selected && <aside className="detail-drawer"><button aria-label="Close evidence preview" onClick={() => setSelected(null)}>×</button><div className="evidence-preview"><Fingerprint size={28} /><span className="eyebrow">Evidence record</span><h2>{selected.label}</h2><p>{selected.notes || 'No annotation was supplied with this evidence reference.'}</p><dl className="fact-list"><div><dt>Evidence ID</dt><dd className="mono">{selected.id}</dd></div><div><dt>Case</dt><dd><Link to={ROUTES.dashboard.case(selected.caseId)}>{selected.caseTitle}</Link></dd></div><div><dt>Type</dt><dd>{titleCase(selected.type)}</dd></div><div><dt>Recorded</dt><dd className="mono">{formatDate(selected.createdAt)}</dd></div></dl>{safeReference(selected.reference) ? <a className="button button--primary" href={safeReference(selected.reference)!} target="_blank" rel="noreferrer">Open secure reference <ExternalLink size={16} /></a> : <p className="form-error">This reference is not a valid HTTPS resource and cannot be opened safely.</p>}</div></aside>}</>;
}
