import { KeyRound, Save, ShieldCheck } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Button, Card, Field, PageHeader, SectionHeader } from '@/components/ui';
import { authRepository } from '@/data/repositories';
import { useAuth } from '@/features/auth/AuthContext';
import { getErrorMessage } from '@/lib/apiClient';

export function ProfilePage() {
  const { user, refreshProfile } = useAuth(); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(''); setError(''); setSaving(true); const data = new FormData(event.currentTarget); try { await authRepository.updateProfile({ name: String(data.get('name')), phone: String(data.get('phone')), district: String(data.get('district')) }); await refreshProfile(); setMessage('Profile details updated.'); } catch (reason) { setError(getErrorMessage(reason)); } finally { setSaving(false); } };
  return <><PageHeader eyebrow="Account" title="Operator profile" description="Maintain the contact and district information attached to your authenticated identity." /><div className="profile-layout"><Card><SectionHeader title="Profile details" description="Changes are sent only to the documented profile endpoint." /><form className="profile-form" onSubmit={submit}><Field label="Display name"><input name="name" defaultValue={user?.name ?? ''} placeholder="Your name" /></Field><Field label="Email"><input value={user?.email ?? ''} disabled /></Field><div className="form-grid"><Field label="Phone"><input name="phone" defaultValue={user?.phone ?? ''} inputMode="tel" placeholder="Official contact number" /></Field><Field label="District"><input name="district" defaultValue={user?.district ?? ''} placeholder="Operational district" /></Field></div>{error && <div className="form-error">{error}</div>}{message && <div className="form-success">{message}</div>}<Button type="submit" disabled={saving}><Save size={17} /> {saving ? 'Saving…' : 'Save profile'}</Button></form></Card><aside><Card><div className="profile-identity"><span><ShieldCheck size={25} /></span><strong>{user?.name || 'Authorized operator'}</strong><p>{user?.email}</p><small>{user?.role} · Identity managed by Netrak authentication</small></div></Card><Card><SectionHeader title="Security" /><div className="security-row"><KeyRound size={19} /><div><strong>Session protected</strong><p>Tokens are refreshed through the documented authentication service and cleared on expiry.</p></div></div></Card></aside></div></>;
}
