import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { EmptyState } from '@/components/ui/EmptyState';
import { Evidence, EvidenceType } from '@/types';
import { formatDateTime } from '@/utils';
import { useAppTheme } from '@/hooks/useAppTheme';
export function EvidenceList({ evidence }: { evidence: Evidence[] }) { const { colors } = useAppTheme(); if (!evidence.length) return <EmptyState iconName="file-upload-outline" title="No evidence attached" message="Audio, screenshots, chat exports, and document references will appear here." />; return <View style={styles.list}>{evidence.map((item) => <View key={item.id} style={[styles.row, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.iconWrap, { backgroundColor: `${colors.tint}15` }]}><MaterialCommunityIcons name={getEvidenceIcon(item.type)} size={20} color={colors.tint} /></View><View style={styles.content}><Text style={[styles.label, { color: colors.text }]}>{item.label}</Text><Text style={[styles.reference, { color: colors.muted }]} numberOfLines={1}>{item.reference}</Text><Text style={[styles.date, { color: colors.muted }]}>{formatDateTime(item.createdAt)}</Text></View></View>)}</View>; }
function getEvidenceIcon(type: EvidenceType) { if (type === 'audio') return 'microphone-outline'; if (type === 'image') return 'image-outline'; if (type === 'video') return 'video-outline'; if (type === 'document') return 'file-document-outline'; if (type === 'chat') return 'message-text-outline'; if (type === 'link') return 'link-variant'; return 'note-text-outline'; }
const styles = StyleSheet.create({ content: { flex: 1 }, date: { fontSize: 11, marginTop: 4 }, iconWrap: { alignItems: 'center', borderRadius: 14, height: 44, justifyContent: 'center', width: 44 }, label: { fontSize: 14, fontWeight: '700' }, list: { gap: 10 }, reference: { fontSize: 13, marginTop: 3 }, row: { alignItems: 'center', borderRadius: 16, borderWidth: 1, flexDirection: 'row', gap: 12, padding: 14 } });
