import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { Card } from '@/components/ui/Card';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { Case } from '@/types';
import { formatDateTime, getIncidentCategoryLabel } from '@/utils';
import { useAppTheme } from '@/hooks/useAppTheme';
export function CaseListItem({ item, onPress }: { item: Case; onPress: () => void }) { const { colors } = useAppTheme(); return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => pressed && styles.pressed}><Card style={styles.card}><View style={styles.header}><View style={styles.titleWrap}><Text style={[styles.title, { color: colors.text }]} numberOfLines={2}>{item.title}</Text><Text style={[styles.meta, { color: colors.tint }]}>{getIncidentCategoryLabel(item.category)}</Text></View><StatusBadge value={item.status} /></View><Text style={[styles.description, { color: colors.muted }]} numberOfLines={2}>{item.description}</Text><View style={styles.footer}><View style={styles.footerItem}><MaterialCommunityIcons name="map-marker-outline" size={15} color={colors.muted} /><Text style={[styles.footerText, { color: colors.muted }]}>{item.location ?? 'Location pending'}</Text></View><Text style={[styles.footerText, { color: colors.muted }]}>{formatDateTime(item.updatedAt)}</Text></View></Card></Pressable>; }
const styles = StyleSheet.create({ card: { marginBottom: 12 }, description: { fontSize: 14, lineHeight: 20, marginTop: 12 }, footer: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 14 }, footerItem: { alignItems: 'center', flexDirection: 'row', gap: 4 }, footerText: { fontSize: 11 }, header: { alignItems: 'flex-start', flexDirection: 'row', gap: 12, justifyContent: 'space-between' }, meta: { fontSize: 11, fontWeight: '700', marginTop: 5 }, pressed: { opacity: 0.72 }, title: { fontSize: 16, fontWeight: '700', letterSpacing: -0.15 }, titleWrap: { flex: 1 } });
