import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { Card } from '@/components/ui/Card';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { ThreatItem } from '@/types';
import { formatDateTime, getIncidentCategoryLabel } from '@/utils';
import { useAppTheme } from '@/hooks/useAppTheme';
export function ThreatCard({ threat }: { threat: ThreatItem }) { const { colors } = useAppTheme(); return <Card style={styles.card}><View style={styles.header}><View style={styles.titleWrap}><Text style={[styles.title, { color: colors.text }]}>{threat.title}</Text><Text style={[styles.category, { color: colors.tint }]}>{getIncidentCategoryLabel(threat.category)}</Text></View><StatusBadge value={threat.level} /></View><Text style={[styles.summary, { color: colors.muted }]}>{threat.summary}</Text><View style={styles.region}><MaterialCommunityIcons name="map-marker-radius-outline" size={16} color={colors.tint} /><Text style={[styles.regionText, { color: colors.text }]}>{threat.region}</Text></View><View style={styles.indicators}>{threat.indicators.map((indicator) => <View key={indicator} style={[styles.indicator, { backgroundColor: colors.surfaceMuted }]}><Text style={[styles.indicatorText, { color: colors.muted }]}>{indicator}</Text></View>)}</View><Text style={[styles.updated, { color: colors.muted }]}>{formatDateTime(threat.updatedAt)}</Text></Card>; }
const styles = StyleSheet.create({ card: { marginBottom: 12 }, category: { fontSize: 11, fontWeight: '700', marginTop: 5 }, header: { alignItems: 'flex-start', flexDirection: 'row', gap: 12, justifyContent: 'space-between' }, indicator: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 }, indicatorText: { fontSize: 11, fontWeight: '600' }, indicators: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 14 }, region: { alignItems: 'center', flexDirection: 'row', gap: 6, marginTop: 14 }, regionText: { fontSize: 13, fontWeight: '600' }, summary: { fontSize: 14, lineHeight: 20, marginTop: 12 }, title: { fontSize: 16, fontWeight: '700' }, titleWrap: { flex: 1 }, updated: { fontSize: 11, marginTop: 14 } });
